import type { ActivityCandidate } from "@/features/trips/activities/activity-types";

/** Activités simulées réalistes (développement, sans clé Places). */
export function getMockActivityCandidates(center: {
  lat: number;
  lng: number;
}): ActivityCandidate[] {
  const { lat, lng } = center;
  return [
    {
      googlePlaceId: "mock_aquarium_001",
      name: "Aquarium du Saint-Laurent",
      address: "1675 Avenue du Parc, Québec",
      city: "Québec",
      latitude: lat + 0.02,
      longitude: lng + 0.01,
      primaryType: "aquarium",
      types: ["aquarium", "tourist_attraction"],
      rating: 4.6,
      reviewCount: 1842,
      priceLevel: "PRICE_LEVEL_MODERATE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat + 0.02},${lng + 0.01}`,
      photoReference: null,
      estimatedVisitMinutes: 120,
      searchZoneKind: "destination",
    },
    {
      googlePlaceId: "mock_park_002",
      name: "Parc national des Chutes",
      address: "Route 138",
      city: "Saint-Tite",
      latitude: lat - 0.05,
      longitude: lng + 0.08,
      primaryType: "national_park",
      types: ["national_park", "park", "hiking_area"],
      rating: 4.8,
      reviewCount: 3201,
      priceLevel: "PRICE_LEVEL_INEXPENSIVE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat - 0.05},${lng + 0.08}`,
      photoReference: null,
      estimatedVisitMinutes: 180,
      searchZoneKind: "route_sample",
    },
    {
      googlePlaceId: "mock_museum_003",
      name: "Musée des sciences interactives",
      address: "12 Rue des Découvertes",
      city: "Lévis",
      latitude: lat + 0.01,
      longitude: lng - 0.03,
      primaryType: "science_museum",
      types: ["science_museum", "museum"],
      rating: 4.5,
      reviewCount: 890,
      priceLevel: "PRICE_LEVEL_MODERATE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat + 0.01},${lng - 0.03}`,
      photoReference: null,
      estimatedVisitMinutes: 150,
      searchZoneKind: "destination",
    },
    {
      googlePlaceId: "mock_view_004",
      name: "Belvédère Panorama",
      address: "Chemin du Cap",
      city: "Cap-Santé",
      latitude: lat + 0.08,
      longitude: lng - 0.06,
      primaryType: "observation_deck",
      types: ["observation_deck", "tourist_attraction"],
      rating: 4.7,
      reviewCount: 654,
      priceLevel: "PRICE_LEVEL_FREE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat + 0.08},${lng - 0.06}`,
      photoReference: null,
      estimatedVisitMinutes: 45,
      searchZoneKind: "route_sample",
    },
    {
      googlePlaceId: "mock_food_005",
      name: "Marché des producteurs locaux",
      address: "45 Place du Marché",
      city: "Québec",
      latitude: lat + 0.015,
      longitude: lng + 0.02,
      primaryType: "market",
      types: ["market", "food_store"],
      rating: 4.4,
      reviewCount: 412,
      priceLevel: "PRICE_LEVEL_INEXPENSIVE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat + 0.015},${lng + 0.02}`,
      photoReference: null,
      estimatedVisitMinutes: 60,
      searchZoneKind: "destination",
    },
    {
      googlePlaceId: "mock_zoo_006",
      name: "Parc animalier des Laurentides",
      address: "880 Rang des Bois",
      city: "Saint-Faustin",
      latitude: lat - 0.03,
      longitude: lng + 0.12,
      primaryType: "zoo",
      types: ["zoo", "wildlife_park"],
      rating: 4.3,
      reviewCount: 2105,
      priceLevel: "PRICE_LEVEL_MODERATE",
      websiteUrl: null,
      googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${lat - 0.03},${lng + 0.12}`,
      photoReference: null,
      estimatedVisitMinutes: 180,
      searchZoneKind: "route_sample",
    },
  ];
}
