/**
 * Contenu informatif du guide /guides/road-trip-famille-quebec.
 * Intention : organiser un road trip familial — distinct de la checklist, du budget et du planificateur.
 */

export const FAMILY_DAY_EXAMPLE = {
  title: "Exemple de journée",
  disclaimer:
    "Horaire fictif à adapter à votre famille. Aucun lieu, commerce, distance ni prix réel n’est recommandé ici.",
  scenario:
    "Scénario fictif pour illustrer un rythme possible : une famille avec enfants, une journée avec route, pauses, repas et une activité.",
  blocks: [
    {
      time: "Matin",
      title: "Départ et première portion de route",
      body: "Départ après le déjeuner, première portion de conduite suivie d’une pause toilettes et collation.",
    },
    {
      time: "Midi",
      title: "Repas et pause mouvement",
      body: "Repas planifié, puis un moment pour marcher ou se dégourdir avant de reprendre la route.",
    },
    {
      time: "Après-midi",
      title: "Activité et seconde portion courte",
      body: "Une activité adaptée à l’énergie du groupe, puis une portion de route plus courte vers l’hébergement.",
    },
    {
      time: "Fin de journée",
      title: "Arrivée et météo à revérifier",
      body: "Installation, repas du soir et coup d’œil aux prévisions pour le lendemain — sans horaire garanti.",
    },
  ],
} as const;

export const FAMILY_GUIDE = {
  meta: {
    title: "Road trip en famille au Québec : guide pratique | Sebavia",
    description:
      "Préparez votre road trip en famille au Québec : pauses, activités, repas, hébergement, météo, carburant et checklist avant le départ.",
  },
  hero: {
    eyebrow: "Guide · Famille",
    title: "Road trip en famille au Québec : bien organiser le voyage",
    body: "Un voyage familial réussi ne dépend pas seulement de la destination : le rythme, les pauses, les repas, les activités et la durée des journées comptent tout autant.",
    primaryCta: {
      href: "/planificateur-road-trip-quebec",
      label: "Voir le planificateur",
    },
    secondaryCta: {
      href: "/assistant-voyage-ia",
      label: "Découvrir l’assistant",
    },
  },
  intro: {
    title: "Adapter le voyage à la famille",
    paragraphs: [
      "Un itinéraire raisonnable pour deux adultes peut être trop chargé pour une famille avec de jeunes enfants. Le bon rythme dépend de l’âge, des habitudes et des besoins de votre famille.",
      "Avant de multiplier les étapes, tenez compte de la tolérance à la voiture, du nombre de pauses, des heures de repas, des siestes éventuelles, des activités, de l’heure d’arrivée, de l’hébergement et de la météo.",
    ],
  },
  toc: [
    { id: "cadre", label: "Commencer par un cadre réaliste" },
    { id: "ages", label: "Tenir compte de l’âge des enfants" },
    { id: "duree", label: "Ne pas calculer uniquement le temps de conduite" },
    { id: "pauses", label: "Planifier les pauses" },
    { id: "activites", label: "Choisir des activités adaptées" },
    { id: "repas", label: "Prévoir les repas et collations" },
    { id: "hebergement", label: "Choisir l’hébergement" },
    { id: "vehicule", label: "Préparer le véhicule" },
    { id: "divertissement", label: "Divertissement pendant le trajet" },
    { id: "meteo", label: "Météo et plan de rechange" },
    { id: "carburant", label: "Carburant et arrêts" },
    { id: "budget", label: "Budget familial" },
    { id: "exemple", label: "Exemple de journée familiale" },
    { id: "participation", label: "Faire participer les enfants" },
    { id: "imprevus", label: "Les imprévus font partie du voyage" },
    { id: "checklist-famille", label: "Checklist familiale" },
    { id: "sebavia", label: "Comment Sebavia peut aider" },
    { id: "limites", label: "Limites de ce guide" },
  ],
  cadre: {
    id: "cadre",
    title: "Commencer par un cadre réaliste",
    lead: "Avant de choisir l’itinéraire, clarifiez ce qui est vraiment tenable pour votre famille.",
    items: [
      "Combien de jours sont disponibles",
      "Combien d’heures de route semblent réalistes par jour",
      "Destination déjà connue ou encore ouverte",
      "Aller-retour ou circuit",
      "Une ou plusieurs nuitées",
      "Intérêts de la famille",
      "Budget approximatif",
      "Saison",
      "Véhicule utilisé",
    ],
    tip: "Un trajet plus court peut laisser davantage de temps pour les activités et les pauses — ce n’est pas une perte, c’est souvent un gain de confort.",
    link: {
      href: "/planificateur-road-trip-quebec",
      label: "Structurer le cadre dans le planificateur",
    },
  },
  ages: {
    id: "ages",
    title: "Tenir compte de l’âge des enfants",
    lead: "Ces blocs sont des pistes, pas des règles absolues. Adaptez-les à votre famille.",
    groups: [
      {
        title: "Jeunes enfants",
        items: [
          "Pauses plus fréquentes",
          "Repas et collations accessibles",
          "Moment de sieste possible",
          "Vêtements de rechange",
          "Activités plus courtes",
          "Heure d’arrivée raisonnable",
        ],
      },
      {
        title: "Enfants d’âge scolaire",
        items: [
          "Activités participatives",
          "Collations et eau",
          "Jeux ou livres pour la route",
          "Petites responsabilités (choisir une pause, ranger un sac)",
          "Variété dans les arrêts",
        ],
      },
      {
        title: "Adolescents",
        items: [
          "Choix d’activités",
          "Autonomie raisonnable",
          "Temps personnel",
          "Accès à la recharge des appareils",
          "Participation à la planification",
        ],
      },
    ],
  },
  duree: {
    id: "duree",
    title: "Ne pas calculer uniquement le temps de conduite",
    lead: "Un trajet affiché à quelques heures peut prendre davantage une fois ajoutés pauses, repas, circulation, toilettes, activités, détours, ravitaillement et installation à l’hébergement.",
    formula:
      "Durée de la journée = conduite + pauses + repas + activités + imprévus",
    tip: "Cette formule est conceptuelle : elle sert à anticiper, pas à fixer une durée universelle.",
  },
  pauses: {
    id: "pauses",
    title: "Planifier les pauses",
    lead: "Une pause peut être intégrée à une activité ou à un repas pour éviter de multiplier les arrêts sans raison.",
    items: [
      "Toilettes",
      "Collation",
      "Repas",
      "Mouvement",
      "Activité courte",
      "Ravitaillement",
      "Arrêt imprévu",
    ],
    tip: "Évitez de conduire trop longtemps sans pause adaptée à votre groupe. Il n’existe pas de durée unique valable pour tous les enfants.",
    fuelStopsLink: {
      href: "/planifier-arrets-carburant",
      label: "Anticiper les arrêts de ravitaillement",
    },
  },
  activites: {
    id: "activites",
    title: "Choisir des activités adaptées",
    lead: "Une activité adaptée dépend de l’âge, des intérêts, de la durée, de la météo, du niveau d’énergie, du temps de déplacement, des heures d’ouverture et de la saison.",
    categories: [
      "Parc",
      "Musée",
      "Activité extérieure",
      "Plage",
      "Centre d’interprétation",
      "Visite gourmande",
      "Activité intérieure",
      "Promenade courte",
    ],
    note: "Vérifiez les restrictions d’âge, les horaires et les conditions auprès du lieu concerné. Sebavia ne garantit pas qu’une activité convient à tous les enfants.",
  },
  repas: {
    id: "repas",
    title: "Prévoir les repas et collations",
    lead: "Une organisation simple réduit le stress sans transformer chaque journée en horaire militaire.",
    items: [
      "Déjeuner avant le départ",
      "Collations accessibles",
      "Eau",
      "Repas planifiés",
      "Options de rechange",
      "Contraintes alimentaires",
      "Heure d’arrivée au restaurant, si prévu",
      "Repas à l’hébergement, si utile",
    ],
    note: "Les besoins alimentaires particuliers doivent être confirmés directement auprès des établissements.",
  },
  hebergement: {
    id: "hebergement",
    title: "Choisir l’hébergement",
    lead: "Au-delà du confort, pensez à la logistique de la journée.",
    items: [
      "Distance après la dernière activité",
      "Heure d’arrivée réaliste",
      "Stationnement",
      "Nombre de lits et espace",
      "Déjeuner inclus ou non",
      "Politique d’annulation",
      "Proximité du prochain départ",
      "Services utiles en famille",
      "Bruit et accessibilité",
    ],
    note: "Sebavia peut aider à proposer ou intégrer un hébergement selon les fonctions disponibles. La réservation demeure à faire auprès du fournisseur ; disponibilités et prix doivent être confirmés.",
  },
  vehicule: {
    id: "vehicule",
    title: "Préparer le véhicule",
    lead: "Checklist générale — pas un diagnostic. Pour toute vérification mécanique, consultez un professionnel qualifié.",
    items: [
      "Carburant ou niveau de charge",
      "Pneus (contrôle visuel simple)",
      "Éclairage",
      "Liquide lave-glace",
      "Documents",
      "Rangement accessible",
      "Chargeurs et câbles",
      "Trousse de premiers soins",
      "Vêtements de rechange",
      "Sacs pour déchets",
      "Eau",
      "Espace pour les bagages",
    ],
    tip: "Vérifiez que les dispositifs de retenue utilisés conviennent à l’enfant et respectent les règles applicables auprès des sources officielles.",
  },
  divertissement: {
    id: "divertissement",
    title: "Divertissement pendant le trajet",
    lead: "Quelques idées générales — sans imposer un usage prolongé d’écran ni juger les choix des parents.",
    items: [
      "Musique",
      "Livres audio",
      "Jeux d’observation",
      "Cartes",
      "Histoires",
      "Petites surprises",
      "Dessin lorsque cela est approprié",
      "Contenu téléchargé à l’avance",
      "Participation au choix des arrêts",
    ],
    tip: "Dans les secteurs où la connexion peut être limitée, téléchargez à l’avance ce dont vous aurez besoin. Sebavia n’est pas présentée ici comme une application entièrement hors ligne.",
  },
  meteo: {
    id: "meteo",
    title: "Météo et plan de rechange",
    lead: "Prévoir une activité extérieure et une option intérieure aide à ajuster la journée sans tout reconstruire.",
    items: [
      "Activité extérieure prévue",
      "Activité intérieure de remplacement",
      "Vêtements adaptés",
      "Pluie, froid, chaleur ou vent selon la saison",
      "Changements de dernière minute",
    ],
    note: "Les prévisions évoluent : revérifiez-les. Sebavia n’est pas une source officielle d’alerte.",
    link: {
      href: "/meteo-voyage",
      label: "Comment Sebavia présente la météo du voyage",
    },
  },
  carburant: {
    id: "carburant",
    title: "Carburant et arrêts",
    lead: "Tenez compte du véhicule, de la consommation, du carburant initial, de l’aller-retour, des détours, des pauses et des régions traversées.",
    links: [
      {
        href: "/calculateur-cout-carburant-voyage",
        label: "Estimer le coût de carburant",
      },
      {
        href: "/planifier-arrets-carburant",
        label: "Planifier les arrêts de carburant",
      },
    ],
  },
  budget: {
    id: "budget",
    title: "Budget familial",
    lead: "Avec une famille, certaines catégories peuvent varier davantage.",
    items: [
      "Hébergement",
      "Repas",
      "Activités",
      "Carburant",
      "Stationnement",
      "Achats imprévus",
      "Collations",
      "Équipement",
      "Marge",
    ],
    tip: "Il n’existe pas de budget moyen universel. Adaptez les montants à votre style de voyage.",
    link: {
      href: "/guides/budget-road-trip-quebec",
      label: "Préparer le budget global du road trip",
    },
  },
  participation: {
    id: "participation",
    title: "Faire participer les enfants",
    lead: "Quelques idées générales et positives — sans publier d’informations personnelles ni de localisation.",
    items: [
      "Choisir une activité",
      "Sélectionner une collation",
      "Suivre le trajet",
      "Préparer un petit sac",
      "Choisir une chanson",
      "Prendre des photos",
      "Tenir un carnet",
      "Voter entre deux options",
    ],
  },
  imprevus: {
    id: "imprevus",
    title: "Les imprévus font partie du voyage",
    lead: "Le plan peut changer : fatigue, météo, fermeture, circulation, malaise, retard, activité plus longue ou changement d’intérêt.",
    items: [
      "Garder une activité facultative",
      "Prévoir une marge dans l’horaire",
      "Avoir une option intérieure",
      "Prévoir une option de repas simple",
      "Se donner la possibilité de raccourcir la journée",
    ],
  },
  checklist: {
    id: "checklist-famille",
    title: "Checklist familiale",
    lead: "Liste imprimable — à adapter, pas à suivre comme une obligation.",
    groups: [
      {
        title: "Avant le départ",
        items: [
          "Dates confirmées",
          "Hébergement confirmé",
          "Trajet et retour",
          "Véhicule",
          "Carburant",
          "Météo",
          "Documents",
          "Dispositifs de retenue appropriés",
          "Médicaments nécessaires",
          "Chargeurs",
          "Vêtements",
          "Repas et collations",
        ],
      },
      {
        title: "Pour la route",
        items: [
          "Eau",
          "Collations",
          "Sacs",
          "Vêtements de rechange",
          "Divertissement",
          "Lingettes ou produits utiles",
          "Trousse générale",
          "Plan des pauses",
        ],
      },
      {
        title: "Pour les activités",
        items: [
          "Réservations",
          "Heures",
          "Restrictions d’âge",
          "Vêtements",
          "Chaussures",
          "Option de rechange",
        ],
      },
    ],
  },
  sebavia: {
    id: "sebavia",
    title: "Comment Sebavia peut aider",
    lead: "Sebavia peut aider à organiser le voyage ; elle ne remplace pas les décisions des parents.",
    links: [
      {
        href: "/planificateur-road-trip-quebec",
        label: "Planificateur",
        body: "Cadre, étapes, activités et rythme du parcours.",
      },
      {
        href: "/assistant-voyage-ia",
        label: "Assistant voyage",
        body: "Démarrer ou ajuster le voyage en conversation.",
      },
      {
        href: "/fonctionnalites",
        label: "Fonctionnalités",
        body: "Adultes, enfants, intérêts et organisation globale.",
      },
      {
        href: "/meteo-voyage",
        label: "Météo du voyage",
        body: "Prévisions liées aux dates et lieux.",
      },
      {
        href: "/calculateur-cout-carburant-voyage",
        label: "Carburant",
        body: "Estimer la part essence du budget.",
      },
      {
        href: "/planifier-arrets-carburant",
        label: "Arrêts de carburant",
        body: "Anticiper l’autonomie et les arrêts.",
      },
      {
        href: "/pricing",
        label: "Tarifs",
        body: "Comprendre les forfaits disponibles.",
      },
    ],
  },
  limits: {
    id: "limites",
    title: "Limites de ce guide",
    paragraphs: [
      "Chaque famille est différente et les besoins varient selon l’âge. Ces conseils restent généraux.",
      "Confirmez les informations des établissements, les conditions météo et routières, ainsi que les règles applicables auprès des sources officielles.",
    ],
  },
  printNote:
    "Astuce : utilisez la fonction d’impression de votre navigateur pour emporter la checklist et l’exemple de journée.",
  finalCta: {
    title: "Transformez votre idée de voyage familial en itinéraire organisé",
    body: "Sebavia peut aider à organiser les étapes, activités, pauses, météo et carburant au même endroit.",
    primary: { href: "/register", label: "Planifier notre voyage" },
    secondary: {
      href: "/planificateur-road-trip-quebec",
      label: "Découvrir le planificateur",
    },
    guidesLink: { href: "/guides", label: "Retour aux guides" },
  },
} as const;
